#!/bin/bash
echo "This script will install some required packages to compile Kirigami64 on Linux."
echo "Package Manager [APT/DNF/PACMAN]: "
read PACMAN
PACMAN=${PACMAN^^}
if [ "$PACMAN" == "APT" ]; then
    sudo apt install build-essential extra-cmake-modules cmake qtbase5-dev qtdeclarative5-dev libqt5svg5-dev qtquickcontrols2-5-dev qml-module-org-kde-kirigami2 kirigami2-dev libkf5i18n-dev gettext libkf5coreaddons-dev qml-module-qtquick-layouts
elif [ "$PACMAN" == "DNF" ]; then
    sudo dnf groupinstall "Development Tools" "Development Libraries"
    sudo dnf install extra-cmake-modules cmake qt5-qtbase-devel qt5-qtdeclarative-devel qt5-qtquickcontrols2-devel kf5-kirigami2 kf5-kirigami2-devel kf5-ki18n-devel kf5-kcoreaddons-devel gettext libgit2 libgit2-devel
elif [ "$PACMAN" == "PACMAN" ]; then
    sudo pacman -S base-devel extra-cmake-modules cmake kirigami2 kde-sdk-meta gettext
fi
