#ifndef CONFIG_HPP
#define CONFIG_HPP

#define PROJECT_NAME "@PROJECT_NAME@"
#define PROJECT_VER  "@PROJECT_VERSION@"
#define PROJECT_VER_SUBTITLE "@PROJECT_VERSION_SUBTITLE@"
#define PROJECT_INSIDE_FLATPAK @FLATPAK_STATE@

#endif // CONFIG_HPP
